<!DOCTYPE HTML>
<html>
<head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="style.css">
	    <link rel="stylesheet" href="Footerdesign.css">	

	
	
	
	
<title>Short Movie</title>
<style>
 .navbar {
  min-height: 140px;
}

.navbar-brand {
  padding: 0 15px;
  height: 80px;
  line-height: 80px;
}

hr.style1{
	border-top: 1px solid #8c8b8b;
}

.topnav .search-container button:hover {
  background: #ccc;
}

@media screen and (max-width: 600px) {
  .topnav .search-container {
    float: none;
  }
  
  body {
    font-family: Arial;
}

* {
    box-sizing: border-box;
}


</style>
</head>
<div class="container"style="margin-top:20px;">
<body style="height:2500px">
<nav class="navbar navbar-inverse navbar-fixed-top"style="opacity:0.8">
  <div class="container-fluid">
    <div class="navbar-header">
      <li><a class="navbar-brand" href="AJENCY_NAV.PHP">ShortMovie<img src=""></a></li>
    </div>
	</div>
    <center><ul class="nav navbar-nav navbar-center"style="margin-left:400px;">
      <li><a href="#">Home</a></li>
      <li><a href="#">Movie</a></li>
      <li><a href="#">Articles</a></li>
      <li><a href="#">Playlist</a></li>
	  <li><a href="#">Submit Films </a></li>
      <li><a href="#">Contact Us</a></li>
	  
    </ul></center>
  
  
  <ul class="nav navbar-nav navbar-right">
      
      <li><a href="login.php"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
</nav>

</head>
<body>



</head>
<body>

<div class="row"style="margin-top:260px;margin-right:400px;">

  </div>
  
	<style>
body {
    font-family: Arial;
}

* {
    box-sizing: border-box;
}

form.example input[type=text] {
    padding: 10px;
    font-size: 17px;
    border: 1px solid grey;
    float: left;
    width: 80%;
    background: white;
}

form.example button {
    float: left;
    width: 20%;
    padding: 10px;
    background: #2196F3;
    color: white;
    font-size: 17px;
    border: 1px solid grey;
    border-left: none;
    cursor: pointer;
}

form.example button:hover {
    background: #0b7dda;
}

form.example::after {
    content: "";
    clear: both;
    display: table;
}
.navbar {
  min-height: 140px;
}

.navbar-brand {
  padding: 0 15px;
  height: 80px;
  line-height: 80px;
}


hr.style1{
	border-top: 1px solid #8c8b8b;
}


.topnav .search-container button:hover {
  background: #ccc;
}

@media screen and (max-width: 600px) {
  .topnav .search-container {
    float: none;
  }
  
  body {
    font-family: Arial;
}

* {
    box-sizing: border-box;
}
h1{
	color:black;
}
.container {
    position: absolute;
    text-align: center;
    color: #e81e1e;
}


</body>
</style>

<div class="container"style="margin-top:-110px;margin-left:-400px;text-align: center;color: #e81e1e;">
<H1>EXPOLRE</H1>
<div class="search-container"style="margin-right:-900px;">
<form class="example" action="/action_page.php" style="margin-left:1300px;max-width:300px;margin-top:-50px;">
  <input type="text" placeholder="Enter your email.." name="search2">
  <button type="submit"id="searchjum"onclick="search()"><i class="fa fa-search"></i></button>
</form>

</body>	
<br>
<hr class="style1">
<br>
	
<div class="container"style="text-align:center;color: #e81e1e;margin-top:-30px;margin-left:-105px;">	
<H3><u>FILTER BY</u></H3>
<br>
<h5 style="margin-left:30px;">Gener:<div class="search-container"style="text-align:center;color: #e81e1e;"name="keyword" id="keyword">
<form class="example" style="margin-left:600px;max-width:300px;margin-top:-30px;">
  
  <input type="text" placeholder="Search by Indian,Chines.." name="search"name="keyword" id="keyword">
  <button type="submit"id="searchjum"onclick="search()"><i class="fa fa-search"></i></button>
</form>	
</h5>

<h5 style="margin-left:30px;">Language:<div class="search-container"style="text-align:center;color: #e81e1e;"name="keyword" id="keyword">
<form class="example" style="margin-left:600px;max-width:300px;margin-top:-10px;">
  
  <input type="text" placeholder="Search by Hindi,Marathi,English" name="search"name="keyword" id="keyword">
  <button type="submit"id="searchjum"onclick="search()"><i class="fa fa-search"></i></button>
</form>		

<div class="search-container"style="margin-right:-500px;margin-top:-70px;"name="keyword" id="keyword">
<h5 style="margin-left:-50px;padding:30px;">Sort by:<form class="example" style="margin-left:1300px;max-width:300px;margin-top:-50px;">
  
  <input type="text" placeholder="Freshness.." name="search"name="keyword" id="keyword">
  <button type="submit"id="searchjum"onclick="search()"><i class="fa fa-search"></i></button>
</form>	
	</div>
</div>

<br>
<hr class="style1"style="margin-left:300px;">
<br>

</body>
<!-- 1st cotainer-->
<div class="container">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/PeJtRX8rYdg?start=166" style="margin-left:400px;height:400px;max-width:600px;padding:-200px;"></iframe>
</div>

<!--2 small containers-->
  <div class="container" style="margin-left:700px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/ND8os7-u6OI	" style="margin-left:300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<div class="container" style="margin-left:600px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/zKwTnNs8Rwo?start=166" style="margin-right:-300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<!--3 contnr down-->

<div class="container"style="margin-top:-100px;">
<div class="embed-responsive embed-responsive-16by9">
  
  </div>

  
  <!--4th contr -->
<div class="container" style="margin-left:-795px;margin-top:-970px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/UjCUKH20h_0?start=166" style="margin-left:450px;height:400px;max-width:610px;padding:-200px;"></iframe>
</div>

  <!--5th contr -->
  <div class="container" style="margin-left:-480px;margin-top:-445px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/bBH0ele7qdw?start=166" alt="video cannot be displayed due to error!! "style="margin-left:300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<div class="container" style="margin-left:590px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/NBJgl-6PT4I?start=166" style="margin-right:-300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>







<!-- next set of block-->
<!-- 1st block-->
<div class="container"style="margin-top:-420px;margin-left:-720px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/GWKNQSDwtO0?start=166"  style="margin-left:400px;height:400px;max-width:600px;padding:-200px;"></iframe>
</div>

<!--2 small containers-->
  <div class="container" style="margin-left:700px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/F1Q2uhbMyGI?start=166" style="margin-left:300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<div class="container" style="margin-left:600px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/9zyic9GsENo?start=166" style="margin-right:-300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<!--3 contnr down-->

<div class="container"style="margin-top:-100px;">
<div class="embed-responsive embed-responsive-16by9">
  
  </div>

  
  <!--4th contr -->
<div class="container" style="margin-left:-795px;margin-top:-970px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/BvXa1n9fjow?start=166" style="margin-left:450px;height:400px;max-width:610px;padding:-200px;"></iframe>
</div>

  <!--5th contr -->
  <div class="container" style="margin-left:-480px;margin-top:-450px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/S509_cqer7g?start=166" alt="video cannot be displayed due to error!! "style="margin-left:300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<div class="container" style="margin-left:590px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/B_enxfU7a_o?start=166" style="margin-right:-300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>







<!-- 1st block-->
<div class="container"style="margin-top:-420px;margin-left:-720px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/v64KOxKVLVg" style="margin-left:400px;height:400px;max-width:600px;padding:-200px;"></iframe>
</div>

<!--2 small containers-->
  <div class="container" style="margin-left:700px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/FTgymgzT3Bw?start=166" style="margin-left:300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<div class="container" style="margin-left:600px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/DCXDyIsPEN8?start=166"  style="margin-right:-300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<!--3 contnr down-->

<div class="container"style="margin-top:-100px;">
<div class="embed-responsive embed-responsive-16by9">
  
  </div>

  
  <!--4th contr -->
<div class="container" style="margin-left:-795px;margin-top:-970px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/FAVvxoABy_M?start=166" style="margin-left:450px;height:400px;max-width:610px;padding:-200px;"></iframe>
</div>

  <!--5th contr -->
  <div class="container" style="margin-left:-480px;margin-top:-450px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/-MlkASchodc?start=166" alt="video cannot be displayed due to error!! "style="margin-left:300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>

<div class="container" style="margin-left:590px;margin-top:-640px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/3HQYdDYSdOk?start=166" style="margin-right:-300px;height:200px;max-width:300px;padding:-200px;"></iframe>
</div>
























<!--horizontal line devider-->
<div class="container"style="margin-top:-200px;">
<hr>
<style>
hr{
	display:block;
	margin-top:-10px;
	margin-bottom:0.5em;
	margin-left:-400px;
	margin-right:auto;
	border-style:inset;
	border-width:1px;
	
	
}

</style>
</div>


<div class="container"style="text-align:center;color: #e81e1e;margin-top:-200px;margin-left:-800px;">	
<H3><u>INDIAN</u></H3>
<br>









<label class="load-more-btn" for="load-more">
    <span class="unloaded">LOAD MORE</span>
    <span class="loaded">VIEW LESS</span>
  </label>  
</div>
<style>


</style>

<!-- 1st block-->
<div class="container"style="margin-top:10px;margin-left:-720px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/krpx6Xo-_KY?start=166" style="margin-left:400px;height:280px;max-width:380px;padding:-200px;"></iframe>
</div>

<div class="container"style="margin-top:-641px;margin-left:420px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/WVPZpVR-7V8?start=166" style="margin-left:400px;height:280px;max-width:380px;padding:-200px;"></iframe>
</div>

<div class="container"style="margin-top:-641px;margin-left:420px;">
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/gabrKeQxqh8?start=166" style="margin-left:400px;height:280px;max-width:380px;padding:-200px;"></iframe>
</div>
</div>


<!-- footter-->

 <style>
#myFooter {
    background-color: #11324d;
    color: white;
    padding-top: 400px;
	margin-left:-130px;
	margin-right:-80px;
	margin-top:-250px;
	
}

#myFooter .footer-copyright {
    background-color: #e81e1e;
    padding-top: 3px;
    padding-bottom: 3px;
    text-align: center;
}

#myFooter .row {
    margin-bottom: 60px;
}

#myFooter .navbar-brand {
    margin-top: 205px;
    height: 265px;
}

#myFooter .footer-copyright p {
    margin: 10px;
    color: #ccc;
}

#myFooter ul {
    list-style-type: none;
    padding-left: 0;
    line-height: 1.7;
}

#myFooter h5 {
    font-size: 18px;
    color: white;
    font-weight: bold;
    margin-top: 30px;
}

#myFooter h2 a{
    font-size: 50px;
    text-align: center;
    color: #fff;
}

#myFooter a {
    color: #d2d1d1;
    text-decoration: none;
}

#myFooter a:hover,
#myFooter a:focus {
    text-decoration: none;
    color: white;
}

#myFooter .social-networks {
    text-align: center;
    padding-top: 30px;
    padding-bottom: 16px;
}

#myFooter .social-networks a {
    font-size: 32px;
    color: #f9f9f9;
    padding: 10px;
    transition: 0.2s;
}

#myFooter .social-networks a:hover {
    text-decoration: none;
}

#myFooter .facebook:hover {
    color: #0077e2;
}

#myFooter .google:hover {
    color: #ef1a1a;
}

#myFooter .twitter:hover {
    color: #00aced;
}

#myFooter .btn {
    color: white;
    background-color:#2ecc71;
    border-radius: 20px;
    border: none;
    width: 150px;
    display: block;
    margin: 0 auto;
    margin-top: 10px;
    line-height: 25px;
}

@media screen and (max-width: 767px) {
    #myFooter {
        text-align: center;
    }
}


/* CSS used for positioning the footers at the bottom of the page. */
/* You can remove this. */

html{
    height: 100%;
}

body{
    display: flex;
    display: -webkit-flex;
    flex-direction: column;
    -webkit-flex-direction: column;
    height: 100%;
}

.content{
   flex: 1 0 auto;
   -webkit-flex: 1 0 auto;
   min-height: 200px;
}

#myFooter{
   flex: 0 0 auto;
   -webkit-flex: 0 0 auto;
}



</style>

    <footer id="myFooter">
        <div class="container" style="margin-top:-450px;height:-100px;padding:50px;">
            <div class="row">
                <div class="col-sm-4">
                    <h2 class="logo"><a href="#"> SHORT MOVIE</a></h2>
					<!--<p> some text</p>-->
                </div>
                <div class="col-sm-2">
                    <a href=""><h5>ABOUT US</h5></a>
                   
                <a href=""><h5>FAQ</h5></a>
                   
				
				</div>
				
				
                <div class="col-sm-2">
                    <a href=""><h5>CONTACT US</h5></a>
                   
				   <a href=""><h5>ARTICLES</h5></a>
                </div>
               
			   <div class="col-sm-2">
                    <a href=""><h5>SUBMIT</h5></a>
                    <a href=""><h5>MOVIES</h5></a>
                </div>
			   
			   <div class="col-sm-2">
                    <a href=""><h5> PLAYLIST</h5></a>
                    <a href=""><h5> BE AN AMBASSADOR</h5></a>
                </div>
			   
                <div class="col-sm-3">
                    <div class="social-networks">
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                    </div>
                    <button type="button" class="btn btn-default">Contact us</button>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>© 2018 </p>
        </div>
    </footer>

</body>

<!--</body>
 <img src="/images/home-banner.jpg" alt="Snow" style="width:100%;">-->
    <script src="js/jquery-1.12.0.min.js"></script>
    <script src="js/search.js"></script>
    <script src="bootstrap.min.js"></script>
	<link href="style.css" rel="stylesheet">
 <script src="js/search.js"></script>
    <link href="home2.css" rel="stylesheet">
    <link rel="stylesheet" href="bootstrap/dist/css/bootstrap.min.css">
</html>
